package eu.europeana.api.commons_sb3.error;


import com.fasterxml.jackson.annotation.*;
import org.springframework.util.StringUtils;

import jakarta.servlet.http.HttpServletRequest;
import java.time.OffsetDateTime;
import java.util.List;

import static eu.europeana.api.commons_sb3.error.EuropeanaErrorConstants.*;


/**
 * This class contains fields to be returned by APIs when an error occurs within the application that is caught by the
 * global exception handler. Note that errors that are uncaught will be generated by the EuropeanaApiErrorAttributes and
 * EuropeanaErrorController classes, so the code here should have similar fields and ordering
 */
@JsonPropertyOrder({context, type, success, status, code, error, message, seeAlso, timestamp, path, trace})
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class EuropeanaApiErrorResponse {

    @JsonProperty(EuropeanaErrorConstants.context)
    private final String context = ERROR_CONTEXT;

    @JsonProperty(EuropeanaErrorConstants.type)
    private final  String type= ErrorResponse;

    @JsonProperty(EuropeanaErrorConstants.success)
    private final boolean success = false;

    @JsonProperty(EuropeanaErrorConstants.status)
    private final int status;

    @JsonProperty(EuropeanaErrorConstants.error)
    private final String error;

    @JsonProperty(EuropeanaErrorConstants.message)
    private final String message;

    @JsonProperty(EuropeanaErrorConstants.seeAlso)
    private final String seeAlso = SEE_ALSO_VALUE;

    @JsonFormat(pattern="yyyy-MM-dd'T'HH:mm:ss'Z'")
    private final OffsetDateTime timestamp = OffsetDateTime.now();

    @JsonProperty(EuropeanaErrorConstants.trace)
    private final String trace;

    @JsonProperty(EuropeanaErrorConstants.path)
    private final String path;

    @JsonProperty(EuropeanaErrorConstants.code)
    private final String code;

    public EuropeanaApiErrorResponse(int status, String error, String message, String trace, String path, String code) {
        this.status = status;
        this.error = error;
        this.message = message;
        this.trace = trace;
        this.path = path;
        this.code = code;
    }

    public String getError() {
        return error;
    }

    public boolean isSuccess() {
        return success;
    }

    public int getStatus() {
        return status;
    }

    public String getMessage() {
        return message;
    }

    public OffsetDateTime getTimestamp() {
        return timestamp;
    }

    public String getTrace() {
        return trace;
    }

    public String getPath() {
        return path;
    }

    public String getCode() {
        return code;
    }

    public String getContext() {
        return context;
    }

    public String getType() {
        return type;
    }

    public String getSeeAlso() {
        return seeAlso;
    }

    public static class Builder {
        private int status;
        private String message;
        private String error;
        private String trace;
        private final String path;
        private String code;

        public Builder(HttpServletRequest httpRequest, Exception e, boolean stacktraceEnabled) {
            this.path = ResponseUtils.getRequestPath(httpRequest);
            boolean includeErrorStack = false;
            String profileParamString = httpRequest.getParameter(profile);
            // check if profile contains debug
            if (StringUtils.hasLength(profileParamString)) {
                includeErrorStack = List.of(profileParamString.split(COMMA))
                        .contains(debug);
            }
            if (stacktraceEnabled && includeErrorStack) {
                this.trace = ResponseUtils.getExceptionStackTrace(e);
            }
        }

        public Builder setStatus(int status) {
            this.status = status;
            return this;
        }

        public Builder setMessage(String message) {
            this.message = message;
            return this;
        }

        public Builder setError(String error) {
            this.error = error;
            return this;
        }

        public Builder setCode(String code) {
            this.code = code;
            return this;
        }

        public EuropeanaApiErrorResponse build() {
            return new EuropeanaApiErrorResponse(status, error, message, trace, path, code);
        }
    }
}
